set_property PACKAGE_PIN T21 [get_ports {running_0[1]}]
set_property PACKAGE_PIN T22 [get_ports {running_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {running_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {running_0[0]}]
set_property PACKAGE_PIN U21 [get_ports {running_1[1]}]
set_property PACKAGE_PIN U22 [get_ports {running_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {running_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {running_1[0]}]
